--- yosys/Makefile	2021-10-21 17:46:08.000000000 +0200
+++ yosys/Makefile	2021-10-21 17:50:02.000000000 +0200
@@ -248,15 +248,17 @@
 LD = emcc
 CXXFLAGS := -std=c++11 $(filter-out -fPIC -ggdb,$(CXXFLAGS))
 ABCMKARGS += ARCHFLAGS="-DABC_USE_STDINT_H -DABC_MEMALIGN=8"
-EMCCFLAGS := -Os -Wno-warn-absolute-paths
-EMCCFLAGS += --memory-init-file 0 --embed-file share -s NO_EXIT_RUNTIME=1
-EMCCFLAGS += -s EXPORTED_FUNCTIONS="['_main','_run','_prompt','_errmsg','_memset']"
-EMCCFLAGS += -s TOTAL_MEMORY=134217728
-EMCCFLAGS += -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'
+EMCC_CXXFLAGS := -Os -Wno-warn-absolute-paths
+EMCC_LDFLAGS := --memory-init-file 0 --embed-file share
+EMCC_LDFLAGS := -s NO_EXIT_RUNTIME=1
+EMCC_LDFLAGS += -s EXPORTED_FUNCTIONS="['_main','_run','_prompt','_errmsg','_memset']"
+EMCC_LDFLAGS += -s TOTAL_MEMORY=134217728
+EMCC_LDFLAGS += -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'
+EMCC_LDFLAGS += -s MODULARIZE=1 -s EXPORT_NAME='Yosys'
 # https://github.com/kripken/emscripten/blob/master/src/settings.js
-CXXFLAGS += $(EMCCFLAGS)
-LDFLAGS += $(EMCCFLAGS)
-LDLIBS =
+CXXFLAGS += $(EMCC_CXXFLAGS)
+LDFLAGS += $(EMCC_LDFLAGS)
+LDLIBS := $(EMCC_LDLIBS)
 EXE = .js
 
 DISABLE_SPAWN := 1
@@ -273,7 +275,7 @@
 	wget -O viz.js.part https://github.com/mdaines/viz.js/releases/download/0.0.3/viz.js
 	mv viz.js.part viz.js
 
-yosysjs-$(YOSYS_VER).zip: yosys.js yosys.wasm viz.js misc/yosysjs/*
+yosysjs-$(YOSYS_VER).zip: yosys.js viz.js misc/yosysjs/*
 	rm -rf yosysjs-$(YOSYS_VER) yosysjs-$(YOSYS_VER).zip
 	mkdir -p yosysjs-$(YOSYS_VER)
 	cp viz.js misc/yosysjs/* yosys.js yosys.wasm yosysjs-$(YOSYS_VER)/
